/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CycleLog = IDL.Record({
  'id' : IDL.Nat,
  'endDate' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'flowIntensity' : IDL.Text,
  'startDate' : IDL.Text,
});
export const AppError = IDL.Variant({
  'alreadyExists' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const Result_5 = IDL.Variant({ 'ok' : CycleLog, 'err' : AppError });
export const SymptomsLog = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'symptoms' : IDL.Vec(IDL.Text),
});
export const Result_12 = IDL.Variant({ 'ok' : SymptomsLog, 'err' : AppError });
export const WaterIntakeEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'amountMl' : IDL.Nat,
  'loggedAt' : IDL.Int,
});
export const Result_11 = IDL.Variant({
  'ok' : WaterIntakeEntry,
  'err' : AppError,
});
export const Result_9 = IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError });
export const Theme = IDL.Variant({
  'ocean' : IDL.Null,
  'cloud' : IDL.Null,
  'night' : IDL.Null,
  'sunset' : IDL.Null,
});
export const FontSize = IDL.Variant({
  'lg' : IDL.Null,
  'sm' : IDL.Null,
  'base' : IDL.Null,
});
export const UserPreferences = IDL.Record({
  'theme' : Theme,
  'highContrast' : IDL.Bool,
  'fontSize' : FontSize,
});
export const OnboardingData = IDL.Record({
  'hasPeriods' : IDL.Opt(IDL.Bool),
  'completed' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'preferences' : UserPreferences,
  'onboarding' : OnboardingData,
});
export const Result_2 = IDL.Variant({ 'ok' : UserProfile, 'err' : AppError });
export const GoalStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'abandoned' : IDL.Null,
});
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'status' : GoalStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'progress' : IDL.Nat,
  'targetDate' : IDL.Opt(IDL.Text),
});
export const Result_4 = IDL.Variant({ 'ok' : Goal, 'err' : AppError });
export const Habit = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'color' : IDL.Text,
  'isArchived' : IDL.Bool,
});
export const Result_10 = IDL.Variant({ 'ok' : Habit, 'err' : AppError });
export const JournalType = IDL.Variant({
  'gratitude' : IDL.Null,
  'regular' : IDL.Null,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'entryType' : JournalType,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'updatedAt' : IDL.Int,
});
export const Result_3 = IDL.Variant({ 'ok' : JournalEntry, 'err' : AppError });
export const DailyWaterLog = IDL.Record({
  'date' : IDL.Text,
  'totalMl' : IDL.Nat,
  'goalMl' : IDL.Nat,
  'entries' : IDL.Vec(WaterIntakeEntry),
});
export const HabitCompletion = IDL.Record({
  'date' : IDL.Text,
  'completed' : IDL.Bool,
  'habitId' : IDL.Nat,
});
export const HabitStreak = IDL.Record({
  'habitId' : IDL.Nat,
  'longestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const MoodEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'emoji' : IDL.Text,
  'score' : IDL.Nat,
});
export const QuizResult = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'answers' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'score' : IDL.Nat,
  'quizId' : IDL.Text,
});
export const SupportContact = IDL.Record({
  'relation' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProfessionalContact = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phone' : IDL.Text,
});
export const SafetyPlan = IDL.Record({
  'warningSigns' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'supportContacts' : IDL.Vec(SupportContact),
  'copingStrategies' : IDL.Vec(IDL.Text),
  'updatedAt' : IDL.Int,
  'professionalContacts' : IDL.Vec(ProfessionalContact),
  'safeEnvironmentNotes' : IDL.Text,
  'reasonsToLive' : IDL.Vec(IDL.Text),
});
export const SleepLog = IDL.Record({
  'id' : IDL.Nat,
  'bedtime' : IDL.Text,
  'date' : IDL.Text,
  'quality' : IDL.Nat,
  'createdAt' : IDL.Int,
  'wakeTime' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const Result_8 = IDL.Variant({ 'ok' : MoodEntry, 'err' : AppError });
export const Result_1 = IDL.Variant({ 'ok' : SleepLog, 'err' : AppError });
export const Result_7 = IDL.Variant({ 'ok' : QuizResult, 'err' : AppError });
export const Result_6 = IDL.Variant({
  'ok' : HabitCompletion,
  'err' : AppError,
});
export const Result = IDL.Variant({ 'ok' : SafetyPlan, 'err' : AppError });

export const idlService = IDL.Service({
  'addCycleLog' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [Result_5],
      [],
    ),
  'addSymptomsLog' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [Result_12], []),
  'addWaterIntake' : IDL.Func([IDL.Text, IDL.Nat], [Result_11], []),
  'archiveHabit' : IDL.Func([IDL.Nat], [Result_9], []),
  'completeOnboarding' : IDL.Func([IDL.Bool], [Result_2], []),
  'createGoal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result_4],
      [],
    ),
  'createHabit' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_10], []),
  'createJournalEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Result_3],
      [],
    ),
  'deleteCycleLog' : IDL.Func([IDL.Nat], [Result_9], []),
  'deleteGoal' : IDL.Func([IDL.Nat], [Result_9], []),
  'deleteHabit' : IDL.Func([IDL.Nat], [Result_9], []),
  'deleteJournalEntry' : IDL.Func([IDL.Nat], [Result_9], []),
  'deleteMoodEntry' : IDL.Func([IDL.Nat], [Result_9], []),
  'deleteQuizResult' : IDL.Func([IDL.Nat], [Result_9], []),
  'deleteSafetyPlan' : IDL.Func([], [Result_9], []),
  'deleteSleepLog' : IDL.Func([IDL.Nat], [Result_9], []),
  'deleteSymptomsLog' : IDL.Func([IDL.Nat], [Result_9], []),
  'deleteWaterEntry' : IDL.Func([IDL.Nat], [Result_9], []),
  'getCycleLogs' : IDL.Func([], [IDL.Vec(CycleLog)], ['query']),
  'getDailyAffirmation' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getDailyWaterLog' : IDL.Func([IDL.Text], [DailyWaterLog], ['query']),
  'getGoals' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Goal)], ['query']),
  'getHabitCompletions' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(HabitCompletion)],
      ['query'],
    ),
  'getHabitStreak' : IDL.Func([IDL.Nat, IDL.Text], [HabitStreak], ['query']),
  'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getJournalEntries' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(JournalEntry)],
      ['query'],
    ),
  'getJournalEntry' : IDL.Func([IDL.Nat], [IDL.Opt(JournalEntry)], ['query']),
  'getMoodEntries' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(MoodEntry)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getQuizResults' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(QuizResult)],
      ['query'],
    ),
  'getSafetyPlan' : IDL.Func([], [IDL.Opt(SafetyPlan)], ['query']),
  'getSleepLogs' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(SleepLog)],
      ['query'],
    ),
  'getSymptomsLogs' : IDL.Func([], [IDL.Vec(SymptomsLog)], ['query']),
  'logMood' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [Result_8],
      [],
    ),
  'logSleep' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [Result_1],
      [],
    ),
  'saveQuizResult' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
      [Result_7],
      [],
    ),
  'setHabitCompletion' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Bool],
      [Result_6],
      [],
    ),
  'setWaterGoal' : IDL.Func([IDL.Nat], [], []),
  'updateCycleLog' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Result_5],
      [],
    ),
  'updateGoal' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [Result_4],
      [],
    ),
  'updateJournalEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [Result_3],
      [],
    ),
  'updatePreferences' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [Result_2],
      [],
    ),
  'updateSleepLog' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [Result_1],
      [],
    ),
  'upsertSafetyPlan' : IDL.Func(
      [
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(SupportContact),
        IDL.Vec(ProfessionalContact),
        IDL.Text,
      ],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CycleLog = IDL.Record({
    'id' : IDL.Nat,
    'endDate' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'flowIntensity' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const AppError = IDL.Variant({
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Result_5 = IDL.Variant({ 'ok' : CycleLog, 'err' : AppError });
  const SymptomsLog = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'symptoms' : IDL.Vec(IDL.Text),
  });
  const Result_12 = IDL.Variant({ 'ok' : SymptomsLog, 'err' : AppError });
  const WaterIntakeEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'amountMl' : IDL.Nat,
    'loggedAt' : IDL.Int,
  });
  const Result_11 = IDL.Variant({ 'ok' : WaterIntakeEntry, 'err' : AppError });
  const Result_9 = IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError });
  const Theme = IDL.Variant({
    'ocean' : IDL.Null,
    'cloud' : IDL.Null,
    'night' : IDL.Null,
    'sunset' : IDL.Null,
  });
  const FontSize = IDL.Variant({
    'lg' : IDL.Null,
    'sm' : IDL.Null,
    'base' : IDL.Null,
  });
  const UserPreferences = IDL.Record({
    'theme' : Theme,
    'highContrast' : IDL.Bool,
    'fontSize' : FontSize,
  });
  const OnboardingData = IDL.Record({
    'hasPeriods' : IDL.Opt(IDL.Bool),
    'completed' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'preferences' : UserPreferences,
    'onboarding' : OnboardingData,
  });
  const Result_2 = IDL.Variant({ 'ok' : UserProfile, 'err' : AppError });
  const GoalStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'abandoned' : IDL.Null,
  });
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'status' : GoalStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'progress' : IDL.Nat,
    'targetDate' : IDL.Opt(IDL.Text),
  });
  const Result_4 = IDL.Variant({ 'ok' : Goal, 'err' : AppError });
  const Habit = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'color' : IDL.Text,
    'isArchived' : IDL.Bool,
  });
  const Result_10 = IDL.Variant({ 'ok' : Habit, 'err' : AppError });
  const JournalType = IDL.Variant({
    'gratitude' : IDL.Null,
    'regular' : IDL.Null,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'entryType' : JournalType,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'updatedAt' : IDL.Int,
  });
  const Result_3 = IDL.Variant({ 'ok' : JournalEntry, 'err' : AppError });
  const DailyWaterLog = IDL.Record({
    'date' : IDL.Text,
    'totalMl' : IDL.Nat,
    'goalMl' : IDL.Nat,
    'entries' : IDL.Vec(WaterIntakeEntry),
  });
  const HabitCompletion = IDL.Record({
    'date' : IDL.Text,
    'completed' : IDL.Bool,
    'habitId' : IDL.Nat,
  });
  const HabitStreak = IDL.Record({
    'habitId' : IDL.Nat,
    'longestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const MoodEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'emoji' : IDL.Text,
    'score' : IDL.Nat,
  });
  const QuizResult = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'answers' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'score' : IDL.Nat,
    'quizId' : IDL.Text,
  });
  const SupportContact = IDL.Record({
    'relation' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProfessionalContact = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SafetyPlan = IDL.Record({
    'warningSigns' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'supportContacts' : IDL.Vec(SupportContact),
    'copingStrategies' : IDL.Vec(IDL.Text),
    'updatedAt' : IDL.Int,
    'professionalContacts' : IDL.Vec(ProfessionalContact),
    'safeEnvironmentNotes' : IDL.Text,
    'reasonsToLive' : IDL.Vec(IDL.Text),
  });
  const SleepLog = IDL.Record({
    'id' : IDL.Nat,
    'bedtime' : IDL.Text,
    'date' : IDL.Text,
    'quality' : IDL.Nat,
    'createdAt' : IDL.Int,
    'wakeTime' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const Result_8 = IDL.Variant({ 'ok' : MoodEntry, 'err' : AppError });
  const Result_1 = IDL.Variant({ 'ok' : SleepLog, 'err' : AppError });
  const Result_7 = IDL.Variant({ 'ok' : QuizResult, 'err' : AppError });
  const Result_6 = IDL.Variant({ 'ok' : HabitCompletion, 'err' : AppError });
  const Result = IDL.Variant({ 'ok' : SafetyPlan, 'err' : AppError });
  
  return IDL.Service({
    'addCycleLog' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [Result_5],
        [],
      ),
    'addSymptomsLog' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [Result_12], []),
    'addWaterIntake' : IDL.Func([IDL.Text, IDL.Nat], [Result_11], []),
    'archiveHabit' : IDL.Func([IDL.Nat], [Result_9], []),
    'completeOnboarding' : IDL.Func([IDL.Bool], [Result_2], []),
    'createGoal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_4],
        [],
      ),
    'createHabit' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_10], []),
    'createJournalEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Result_3],
        [],
      ),
    'deleteCycleLog' : IDL.Func([IDL.Nat], [Result_9], []),
    'deleteGoal' : IDL.Func([IDL.Nat], [Result_9], []),
    'deleteHabit' : IDL.Func([IDL.Nat], [Result_9], []),
    'deleteJournalEntry' : IDL.Func([IDL.Nat], [Result_9], []),
    'deleteMoodEntry' : IDL.Func([IDL.Nat], [Result_9], []),
    'deleteQuizResult' : IDL.Func([IDL.Nat], [Result_9], []),
    'deleteSafetyPlan' : IDL.Func([], [Result_9], []),
    'deleteSleepLog' : IDL.Func([IDL.Nat], [Result_9], []),
    'deleteSymptomsLog' : IDL.Func([IDL.Nat], [Result_9], []),
    'deleteWaterEntry' : IDL.Func([IDL.Nat], [Result_9], []),
    'getCycleLogs' : IDL.Func([], [IDL.Vec(CycleLog)], ['query']),
    'getDailyAffirmation' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getDailyWaterLog' : IDL.Func([IDL.Text], [DailyWaterLog], ['query']),
    'getGoals' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Goal)], ['query']),
    'getHabitCompletions' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(HabitCompletion)],
        ['query'],
      ),
    'getHabitStreak' : IDL.Func([IDL.Nat, IDL.Text], [HabitStreak], ['query']),
    'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getJournalEntries' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'getJournalEntry' : IDL.Func([IDL.Nat], [IDL.Opt(JournalEntry)], ['query']),
    'getMoodEntries' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(MoodEntry)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getQuizResults' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(QuizResult)],
        ['query'],
      ),
    'getSafetyPlan' : IDL.Func([], [IDL.Opt(SafetyPlan)], ['query']),
    'getSleepLogs' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(SleepLog)],
        ['query'],
      ),
    'getSymptomsLogs' : IDL.Func([], [IDL.Vec(SymptomsLog)], ['query']),
    'logMood' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [Result_8],
        [],
      ),
    'logSleep' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [Result_1],
        [],
      ),
    'saveQuizResult' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
        [Result_7],
        [],
      ),
    'setHabitCompletion' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Bool],
        [Result_6],
        [],
      ),
    'setWaterGoal' : IDL.Func([IDL.Nat], [], []),
    'updateCycleLog' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Result_5],
        [],
      ),
    'updateGoal' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [Result_4],
        [],
      ),
    'updateJournalEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [Result_3],
        [],
      ),
    'updatePreferences' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [Result_2],
        [],
      ),
    'updateSleepLog' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [Result_1],
        [],
      ),
    'upsertSafetyPlan' : IDL.Func(
        [
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(SupportContact),
          IDL.Vec(ProfessionalContact),
          IDL.Text,
        ],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };