/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppError = { 'alreadyExists' : null } |
  { 'invalidInput' : string } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export interface CycleLog {
  'id' : bigint,
  'endDate' : [] | [string],
  'createdAt' : bigint,
  'flowIntensity' : string,
  'startDate' : string,
}
export interface DailyWaterLog {
  'date' : string,
  'totalMl' : bigint,
  'goalMl' : bigint,
  'entries' : Array<WaterIntakeEntry>,
}
export type FontSize = { 'lg' : null } |
  { 'sm' : null } |
  { 'base' : null };
export interface Goal {
  'id' : bigint,
  'status' : GoalStatus,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'progress' : bigint,
  'targetDate' : [] | [string],
}
export type GoalStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'abandoned' : null };
export interface Habit {
  'id' : bigint,
  'icon' : string,
  'name' : string,
  'createdAt' : bigint,
  'color' : string,
  'isArchived' : boolean,
}
export interface HabitCompletion {
  'date' : string,
  'completed' : boolean,
  'habitId' : bigint,
}
export interface HabitStreak {
  'habitId' : bigint,
  'longestStreak' : bigint,
  'currentStreak' : bigint,
}
export interface JournalEntry {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'entryType' : JournalType,
  'date' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'updatedAt' : bigint,
}
export type JournalType = { 'gratitude' : null } |
  { 'regular' : null };
export interface MoodEntry {
  'id' : bigint,
  'date' : string,
  'note' : [] | [string],
  'createdAt' : bigint,
  'emoji' : string,
  'score' : bigint,
}
export interface OnboardingData {
  'hasPeriods' : [] | [boolean],
  'completed' : boolean,
}
export interface ProfessionalContact {
  'name' : string,
  'role' : string,
  'phone' : string,
}
export interface QuizResult {
  'id' : bigint,
  'date' : string,
  'answers' : Array<string>,
  'createdAt' : bigint,
  'score' : bigint,
  'quizId' : string,
}
export type Result = { 'ok' : SafetyPlan } |
  { 'err' : AppError };
export type Result_1 = { 'ok' : SleepLog } |
  { 'err' : AppError };
export type Result_10 = { 'ok' : Habit } |
  { 'err' : AppError };
export type Result_11 = { 'ok' : WaterIntakeEntry } |
  { 'err' : AppError };
export type Result_12 = { 'ok' : SymptomsLog } |
  { 'err' : AppError };
export type Result_2 = { 'ok' : UserProfile } |
  { 'err' : AppError };
export type Result_3 = { 'ok' : JournalEntry } |
  { 'err' : AppError };
export type Result_4 = { 'ok' : Goal } |
  { 'err' : AppError };
export type Result_5 = { 'ok' : CycleLog } |
  { 'err' : AppError };
export type Result_6 = { 'ok' : HabitCompletion } |
  { 'err' : AppError };
export type Result_7 = { 'ok' : QuizResult } |
  { 'err' : AppError };
export type Result_8 = { 'ok' : MoodEntry } |
  { 'err' : AppError };
export type Result_9 = { 'ok' : null } |
  { 'err' : AppError };
export interface SafetyPlan {
  'warningSigns' : Array<string>,
  'userId' : Principal,
  'supportContacts' : Array<SupportContact>,
  'copingStrategies' : Array<string>,
  'updatedAt' : bigint,
  'professionalContacts' : Array<ProfessionalContact>,
  'safeEnvironmentNotes' : string,
  'reasonsToLive' : Array<string>,
}
export interface SleepLog {
  'id' : bigint,
  'bedtime' : string,
  'date' : string,
  'quality' : bigint,
  'createdAt' : bigint,
  'wakeTime' : string,
  'notes' : [] | [string],
}
export interface SupportContact {
  'relation' : string,
  'name' : string,
  'phone' : string,
}
export interface SymptomsLog {
  'id' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'symptoms' : Array<string>,
}
export type Theme = { 'ocean' : null } |
  { 'cloud' : null } |
  { 'night' : null } |
  { 'sunset' : null };
export interface UserPreferences {
  'theme' : Theme,
  'highContrast' : boolean,
  'fontSize' : FontSize,
}
export interface UserProfile {
  'userId' : Principal,
  'createdAt' : bigint,
  'preferences' : UserPreferences,
  'onboarding' : OnboardingData,
}
export interface WaterIntakeEntry {
  'id' : bigint,
  'date' : string,
  'amountMl' : bigint,
  'loggedAt' : bigint,
}
export interface _SERVICE {
  'addCycleLog' : ActorMethod<[string, [] | [string], string], Result_5>,
  'addSymptomsLog' : ActorMethod<[string, Array<string>], Result_12>,
  'addWaterIntake' : ActorMethod<[string, bigint], Result_11>,
  'archiveHabit' : ActorMethod<[bigint], Result_9>,
  'completeOnboarding' : ActorMethod<[boolean], Result_2>,
  'createGoal' : ActorMethod<[string, string, [] | [string]], Result_4>,
  'createHabit' : ActorMethod<[string, string, string], Result_10>,
  'createJournalEntry' : ActorMethod<
    [string, string, string, string, Array<string>],
    Result_3
  >,
  'deleteCycleLog' : ActorMethod<[bigint], Result_9>,
  'deleteGoal' : ActorMethod<[bigint], Result_9>,
  'deleteHabit' : ActorMethod<[bigint], Result_9>,
  'deleteJournalEntry' : ActorMethod<[bigint], Result_9>,
  'deleteMoodEntry' : ActorMethod<[bigint], Result_9>,
  'deleteQuizResult' : ActorMethod<[bigint], Result_9>,
  'deleteSafetyPlan' : ActorMethod<[], Result_9>,
  'deleteSleepLog' : ActorMethod<[bigint], Result_9>,
  'deleteSymptomsLog' : ActorMethod<[bigint], Result_9>,
  'deleteWaterEntry' : ActorMethod<[bigint], Result_9>,
  'getCycleLogs' : ActorMethod<[], Array<CycleLog>>,
  'getDailyAffirmation' : ActorMethod<[bigint], string>,
  'getDailyWaterLog' : ActorMethod<[string], DailyWaterLog>,
  'getGoals' : ActorMethod<[[] | [string]], Array<Goal>>,
  'getHabitCompletions' : ActorMethod<[string, string], Array<HabitCompletion>>,
  'getHabitStreak' : ActorMethod<[bigint, string], HabitStreak>,
  'getHabits' : ActorMethod<[], Array<Habit>>,
  'getJournalEntries' : ActorMethod<[[] | [string]], Array<JournalEntry>>,
  'getJournalEntry' : ActorMethod<[bigint], [] | [JournalEntry]>,
  'getMoodEntries' : ActorMethod<[string, string], Array<MoodEntry>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getQuizResults' : ActorMethod<[[] | [string]], Array<QuizResult>>,
  'getSafetyPlan' : ActorMethod<[], [] | [SafetyPlan]>,
  'getSleepLogs' : ActorMethod<[string, string], Array<SleepLog>>,
  'getSymptomsLogs' : ActorMethod<[], Array<SymptomsLog>>,
  'logMood' : ActorMethod<[string, string, bigint, [] | [string]], Result_8>,
  'logSleep' : ActorMethod<
    [string, string, string, bigint, [] | [string]],
    Result_1
  >,
  'saveQuizResult' : ActorMethod<
    [string, string, bigint, Array<string>],
    Result_7
  >,
  'setHabitCompletion' : ActorMethod<[bigint, string, boolean], Result_6>,
  'setWaterGoal' : ActorMethod<[bigint], undefined>,
  'updateCycleLog' : ActorMethod<
    [bigint, [] | [string], [] | [string]],
    Result_5
  >,
  'updateGoal' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
    ],
    Result_4
  >,
  'updateJournalEntry' : ActorMethod<
    [bigint, [] | [string], [] | [string], [] | [Array<string>]],
    Result_3
  >,
  'updatePreferences' : ActorMethod<[string, string, boolean], Result_2>,
  'updateSleepLog' : ActorMethod<
    [bigint, [] | [string], [] | [string], [] | [bigint], [] | [string]],
    Result_1
  >,
  'upsertSafetyPlan' : ActorMethod<
    [
      Array<string>,
      Array<string>,
      Array<string>,
      Array<SupportContact>,
      Array<ProfessionalContact>,
      string,
    ],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];