/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserPreferences {
    theme: Theme;
    highContrast: boolean;
    fontSize: FontSize;
}
export type Result_2 = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: AppError;
};
export interface ProfessionalContact {
    name: string;
    role: string;
    phone: string;
}
export interface Habit {
    id: bigint;
    icon: string;
    name: string;
    createdAt: bigint;
    color: string;
    isArchived: boolean;
}
export type AppError = {
    __kind__: "alreadyExists";
    alreadyExists: null;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export type Result_5 = {
    __kind__: "ok";
    ok: CycleLog;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result_1 = {
    __kind__: "ok";
    ok: SleepLog;
} | {
    __kind__: "err";
    err: AppError;
};
export interface MoodEntry {
    id: bigint;
    date: string;
    note?: string;
    createdAt: bigint;
    emoji: string;
    score: bigint;
}
export type Result_4 = {
    __kind__: "ok";
    ok: Goal;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result_11 = {
    __kind__: "ok";
    ok: WaterIntakeEntry;
} | {
    __kind__: "err";
    err: AppError;
};
export interface HabitCompletion {
    date: string;
    completed: boolean;
    habitId: bigint;
}
export type Result_7 = {
    __kind__: "ok";
    ok: QuizResult;
} | {
    __kind__: "err";
    err: AppError;
};
export interface SupportContact {
    relation: string;
    name: string;
    phone: string;
}
export interface OnboardingData {
    hasPeriods?: boolean;
    completed: boolean;
}
export interface HabitStreak {
    habitId: bigint;
    longestStreak: bigint;
    currentStreak: bigint;
}
export type Result_6 = {
    __kind__: "ok";
    ok: HabitCompletion;
} | {
    __kind__: "err";
    err: AppError;
};
export interface SafetyPlan {
    warningSigns: Array<string>;
    userId: Principal;
    supportContacts: Array<SupportContact>;
    copingStrategies: Array<string>;
    updatedAt: bigint;
    professionalContacts: Array<ProfessionalContact>;
    safeEnvironmentNotes: string;
    reasonsToLive: Array<string>;
}
export interface QuizResult {
    id: bigint;
    date: string;
    answers: Array<string>;
    createdAt: bigint;
    score: bigint;
    quizId: string;
}
export type Result_12 = {
    __kind__: "ok";
    ok: SymptomsLog;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result_9 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AppError;
};
export interface DailyWaterLog {
    date: string;
    totalMl: bigint;
    goalMl: bigint;
    entries: Array<WaterIntakeEntry>;
}
export interface WaterIntakeEntry {
    id: bigint;
    date: string;
    amountMl: bigint;
    loggedAt: bigint;
}
export interface SleepLog {
    id: bigint;
    bedtime: string;
    date: string;
    quality: bigint;
    createdAt: bigint;
    wakeTime: string;
    notes?: string;
}
export type Result = {
    __kind__: "ok";
    ok: SafetyPlan;
} | {
    __kind__: "err";
    err: AppError;
};
export interface SymptomsLog {
    id: bigint;
    date: string;
    createdAt: bigint;
    symptoms: Array<string>;
}
export type Result_3 = {
    __kind__: "ok";
    ok: JournalEntry;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result_10 = {
    __kind__: "ok";
    ok: Habit;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result_8 = {
    __kind__: "ok";
    ok: MoodEntry;
} | {
    __kind__: "err";
    err: AppError;
};
export interface JournalEntry {
    id: bigint;
    title: string;
    content: string;
    entryType: JournalType;
    date: string;
    createdAt: bigint;
    tags: Array<string>;
    updatedAt: bigint;
}
export interface CycleLog {
    id: bigint;
    endDate?: string;
    createdAt: bigint;
    flowIntensity: string;
    startDate: string;
}
export interface UserProfile {
    userId: Principal;
    createdAt: bigint;
    preferences: UserPreferences;
    onboarding: OnboardingData;
}
export interface Goal {
    id: bigint;
    status: GoalStatus;
    title: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    progress: bigint;
    targetDate?: string;
}
export enum FontSize {
    lg = "lg",
    sm = "sm",
    base = "base"
}
export enum GoalStatus {
    active = "active",
    completed = "completed",
    abandoned = "abandoned"
}
export enum JournalType {
    gratitude = "gratitude",
    regular = "regular"
}
export enum Theme {
    ocean = "ocean",
    cloud = "cloud",
    night = "night",
    sunset = "sunset"
}
export interface backendInterface {
    addCycleLog(startDate: string, endDate: string | null, flowIntensity: string): Promise<Result_5>;
    addSymptomsLog(date: string, symptoms: Array<string>): Promise<Result_12>;
    addWaterIntake(date: string, amountMl: bigint): Promise<Result_11>;
    archiveHabit(habitId: bigint): Promise<Result_9>;
    completeOnboarding(hasPeriods: boolean): Promise<Result_2>;
    createGoal(title: string, description: string, targetDate: string | null): Promise<Result_4>;
    createHabit(name: string, color: string, icon: string): Promise<Result_10>;
    createJournalEntry(date: string, title: string, content: string, entryType: string, tags: Array<string>): Promise<Result_3>;
    deleteCycleLog(logId: bigint): Promise<Result_9>;
    deleteGoal(goalId: bigint): Promise<Result_9>;
    deleteHabit(habitId: bigint): Promise<Result_9>;
    deleteJournalEntry(entryId: bigint): Promise<Result_9>;
    deleteMoodEntry(entryId: bigint): Promise<Result_9>;
    deleteQuizResult(resultId: bigint): Promise<Result_9>;
    deleteSafetyPlan(): Promise<Result_9>;
    deleteSleepLog(logId: bigint): Promise<Result_9>;
    deleteSymptomsLog(logId: bigint): Promise<Result_9>;
    deleteWaterEntry(entryId: bigint): Promise<Result_9>;
    getCycleLogs(): Promise<Array<CycleLog>>;
    getDailyAffirmation(dayOfYear: bigint): Promise<string>;
    getDailyWaterLog(date: string): Promise<DailyWaterLog>;
    getGoals(status: string | null): Promise<Array<Goal>>;
    getHabitCompletions(fromDate: string, toDate: string): Promise<Array<HabitCompletion>>;
    getHabitStreak(habitId: bigint, today: string): Promise<HabitStreak>;
    getHabits(): Promise<Array<Habit>>;
    getJournalEntries(entryType: string | null): Promise<Array<JournalEntry>>;
    getJournalEntry(entryId: bigint): Promise<JournalEntry | null>;
    getMoodEntries(fromDate: string, toDate: string): Promise<Array<MoodEntry>>;
    getMyProfile(): Promise<UserProfile | null>;
    getQuizResults(quizId: string | null): Promise<Array<QuizResult>>;
    getSafetyPlan(): Promise<SafetyPlan | null>;
    getSleepLogs(fromDate: string, toDate: string): Promise<Array<SleepLog>>;
    getSymptomsLogs(): Promise<Array<SymptomsLog>>;
    logMood(date: string, emoji: string, score: bigint, note: string | null): Promise<Result_8>;
    logSleep(date: string, bedtime: string, wakeTime: string, quality: bigint, notes: string | null): Promise<Result_1>;
    saveQuizResult(quizId: string, date: string, score: bigint, answers: Array<string>): Promise<Result_7>;
    setHabitCompletion(habitId: bigint, date: string, completed: boolean): Promise<Result_6>;
    setWaterGoal(goalMl: bigint): Promise<void>;
    updateCycleLog(logId: bigint, endDate: string | null, flowIntensity: string | null): Promise<Result_5>;
    updateGoal(goalId: bigint, title: string | null, description: string | null, targetDate: string | null, status: string | null, progress: bigint | null): Promise<Result_4>;
    updateJournalEntry(entryId: bigint, title: string | null, content: string | null, tags: Array<string> | null): Promise<Result_3>;
    updatePreferences(theme: string, fontSize: string, highContrast: boolean): Promise<Result_2>;
    updateSleepLog(logId: bigint, bedtime: string | null, wakeTime: string | null, quality: bigint | null, notes: string | null): Promise<Result_1>;
    upsertSafetyPlan(reasonsToLive: Array<string>, warningSigns: Array<string>, copingStrategies: Array<string>, supportContacts: Array<SupportContact>, professionalContacts: Array<ProfessionalContact>, safeEnvironmentNotes: string): Promise<Result>;
}
import type { AppError as _AppError, CycleLog as _CycleLog, FontSize as _FontSize, Goal as _Goal, GoalStatus as _GoalStatus, Habit as _Habit, HabitCompletion as _HabitCompletion, JournalEntry as _JournalEntry, JournalType as _JournalType, MoodEntry as _MoodEntry, OnboardingData as _OnboardingData, QuizResult as _QuizResult, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_11 as _Result_11, Result_12 as _Result_12, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, SafetyPlan as _SafetyPlan, SleepLog as _SleepLog, SymptomsLog as _SymptomsLog, Theme as _Theme, UserPreferences as _UserPreferences, UserProfile as _UserProfile, WaterIntakeEntry as _WaterIntakeEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCycleLog(arg0: string, arg1: string | null, arg2: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.addCycleLog(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Result_5_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCycleLog(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Result_5_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addSymptomsLog(arg0: string, arg1: Array<string>): Promise<Result_12> {
        if (this.processError) {
            try {
                const result = await this.actor.addSymptomsLog(arg0, arg1);
                return from_candid_Result_12_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSymptomsLog(arg0, arg1);
            return from_candid_Result_12_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addWaterIntake(arg0: string, arg1: bigint): Promise<Result_11> {
        if (this.processError) {
            try {
                const result = await this.actor.addWaterIntake(arg0, arg1);
                return from_candid_Result_11_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWaterIntake(arg0, arg1);
            return from_candid_Result_11_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async archiveHabit(arg0: bigint): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveHabit(arg0);
                return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveHabit(arg0);
            return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeOnboarding(arg0: boolean): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOnboarding(arg0);
                return from_candid_Result_2_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOnboarding(arg0);
            return from_candid_Result_2_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGoal(arg0: string, arg1: string, arg2: string | null): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_4_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_4_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async createHabit(arg0: string, arg1: string, arg2: string): Promise<Result_10> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabit(arg0, arg1, arg2);
                return from_candid_Result_10_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabit(arg0, arg1, arg2);
            return from_candid_Result_10_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async createJournalEntry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.createJournalEntry(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_3_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJournalEntry(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_3_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCycleLog(arg0: bigint): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCycleLog(arg0);
                return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCycleLog(arg0);
            return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteGoal(arg0: bigint): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteHabit(arg0: bigint): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHabit(arg0);
                return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHabit(arg0);
            return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteJournalEntry(arg0: bigint): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMoodEntry(arg0: bigint): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMoodEntry(arg0);
                return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMoodEntry(arg0);
            return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteQuizResult(arg0: bigint): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuizResult(arg0);
                return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuizResult(arg0);
            return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSafetyPlan(): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSafetyPlan();
                return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSafetyPlan();
            return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSleepLog(arg0: bigint): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSleepLog(arg0);
                return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSleepLog(arg0);
            return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSymptomsLog(arg0: bigint): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSymptomsLog(arg0);
                return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSymptomsLog(arg0);
            return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteWaterEntry(arg0: bigint): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWaterEntry(arg0);
                return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWaterEntry(arg0);
            return from_candid_Result_9_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCycleLogs(): Promise<Array<CycleLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCycleLogs();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCycleLogs();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyAffirmation(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyAffirmation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyAffirmation(arg0);
            return result;
        }
    }
    async getDailyWaterLog(arg0: string): Promise<DailyWaterLog> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyWaterLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyWaterLog(arg0);
            return result;
        }
    }
    async getGoals(arg0: string | null): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoals(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoals(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabitCompletions(arg0: string, arg1: string): Promise<Array<HabitCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabitCompletions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabitCompletions(arg0, arg1);
            return result;
        }
    }
    async getHabitStreak(arg0: bigint, arg1: string): Promise<HabitStreak> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabitStreak(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabitStreak(arg0, arg1);
            return result;
        }
    }
    async getHabits(): Promise<Array<Habit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabits();
            return result;
        }
    }
    async getJournalEntries(arg0: string | null): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntries(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntries(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournalEntry(arg0: bigint): Promise<JournalEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntry(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntry(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMoodEntries(arg0: string, arg1: string): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodEntries(arg0, arg1);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodEntries(arg0, arg1);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizResults(arg0: string | null): Promise<Array<QuizResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizResults(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizResults(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getSafetyPlan(): Promise<SafetyPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSafetyPlan();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSafetyPlan();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSleepLogs(arg0: string, arg1: string): Promise<Array<SleepLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSleepLogs(arg0, arg1);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSleepLogs(arg0, arg1);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSymptomsLogs(): Promise<Array<SymptomsLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSymptomsLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSymptomsLogs();
            return result;
        }
    }
    async logMood(arg0: string, arg1: string, arg2: bigint, arg3: string | null): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.logMood(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_8_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMood(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_8_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async logSleep(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string | null): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.logSleep(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_1_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSleep(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_1_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveQuizResult(arg0: string, arg1: string, arg2: bigint, arg3: Array<string>): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuizResult(arg0, arg1, arg2, arg3);
                return from_candid_Result_7_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuizResult(arg0, arg1, arg2, arg3);
            return from_candid_Result_7_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async setHabitCompletion(arg0: bigint, arg1: string, arg2: boolean): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.setHabitCompletion(arg0, arg1, arg2);
                return from_candid_Result_6_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHabitCompletion(arg0, arg1, arg2);
            return from_candid_Result_6_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async setWaterGoal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWaterGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWaterGoal(arg0);
            return result;
        }
    }
    async updateCycleLog(arg0: bigint, arg1: string | null, arg2: string | null): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCycleLog(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_5_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCycleLog(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_5_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGoal(arg0: bigint, arg1: string | null, arg2: string | null, arg3: string | null, arg4: string | null, arg5: bigint | null): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoal(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n62(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Result_4_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoal(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n62(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Result_4_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateJournalEntry(arg0: bigint, arg1: string | null, arg2: string | null, arg3: Array<string> | null): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJournalEntry(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n63(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_3_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJournalEntry(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n63(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_3_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePreferences(arg0: string, arg1: string, arg2: boolean): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreferences(arg0, arg1, arg2);
                return from_candid_Result_2_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreferences(arg0, arg1, arg2);
            return from_candid_Result_2_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSleepLog(arg0: bigint, arg1: string | null, arg2: string | null, arg3: bigint | null, arg4: string | null): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSleepLog(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n62(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_1_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSleepLog(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n62(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_1_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertSafetyPlan(arg0: Array<string>, arg1: Array<string>, arg2: Array<string>, arg3: Array<SupportContact>, arg4: Array<ProfessionalContact>, arg5: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertSafetyPlan(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Result_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertSafetyPlan(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Result_n64(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppError_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppError): AppError {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_CycleLog_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CycleLog): CycleLog {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_FontSize_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FontSize): FontSize {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_GoalStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalStatus): GoalStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_JournalEntry_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JournalEntry): JournalEntry {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_JournalType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JournalType): JournalType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_MoodEntry_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoodEntry): MoodEntry {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_OnboardingData_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OnboardingData): OnboardingData {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Result_10_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_10): Result_10 {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Result_11_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_11): Result_11 {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_12_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_12): Result_12 {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Result_9_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_9): Result_9 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_SleepLog_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SleepLog): SleepLog {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Theme_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Theme): Theme {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserPreferences_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPreferences): UserPreferences {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JournalEntry]): JournalEntry | null {
    return value.length === 0 ? null : from_candid_JournalEntry_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SafetyPlan]): SafetyPlan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: Principal;
    createdAt: bigint;
    preferences: _UserPreferences;
    onboarding: _OnboardingData;
}): {
    userId: Principal;
    createdAt: bigint;
    preferences: UserPreferences;
    onboarding: OnboardingData;
} {
    return {
        userId: value.userId,
        createdAt: value.createdAt,
        preferences: from_candid_UserPreferences_n19(_uploadFile, _downloadFile, value.preferences),
        onboarding: from_candid_OnboardingData_n25(_uploadFile, _downloadFile, value.onboarding)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: _Theme;
    highContrast: boolean;
    fontSize: _FontSize;
}): {
    theme: Theme;
    highContrast: boolean;
    fontSize: FontSize;
} {
    return {
        theme: from_candid_Theme_n21(_uploadFile, _downloadFile, value.theme),
        highContrast: value.highContrast,
        fontSize: from_candid_FontSize_n23(_uploadFile, _downloadFile, value.fontSize)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasPeriods: [] | [boolean];
    completed: boolean;
}): {
    hasPeriods?: boolean;
    completed: boolean;
} {
    return {
        hasPeriods: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.hasPeriods)),
        completed: value.completed
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _GoalStatus;
    title: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    progress: bigint;
    targetDate: [] | [string];
}): {
    id: bigint;
    status: GoalStatus;
    title: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    progress: bigint;
    targetDate?: string;
} {
    return {
        id: value.id,
        status: from_candid_GoalStatus_n32(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        progress: value.progress,
        targetDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.targetDate))
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    entryType: _JournalType;
    date: string;
    createdAt: bigint;
    tags: Array<string>;
    updatedAt: bigint;
}): {
    id: bigint;
    title: string;
    content: string;
    entryType: JournalType;
    date: string;
    createdAt: bigint;
    tags: Array<string>;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        entryType: from_candid_JournalType_n40(_uploadFile, _downloadFile, value.entryType),
        date: value.date,
        createdAt: value.createdAt,
        tags: value.tags,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: string;
    note: [] | [string];
    createdAt: bigint;
    emoji: string;
    score: bigint;
}): {
    id: bigint;
    date: string;
    note?: string;
    createdAt: bigint;
    emoji: string;
    score: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        note: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.note)),
        createdAt: value.createdAt,
        emoji: value.emoji,
        score: value.score
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    endDate: [] | [string];
    createdAt: bigint;
    flowIntensity: string;
    startDate: string;
}): {
    id: bigint;
    endDate?: string;
    createdAt: bigint;
    flowIntensity: string;
    startDate: string;
} {
    return {
        id: value.id,
        endDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.endDate)),
        createdAt: value.createdAt,
        flowIntensity: value.flowIntensity,
        startDate: value.startDate
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bedtime: string;
    date: string;
    quality: bigint;
    createdAt: bigint;
    wakeTime: string;
    notes: [] | [string];
}): {
    id: bigint;
    bedtime: string;
    date: string;
    quality: bigint;
    createdAt: bigint;
    wakeTime: string;
    notes?: string;
} {
    return {
        id: value.id,
        bedtime: value.bedtime,
        date: value.date,
        quality: value.quality,
        createdAt: value.createdAt,
        wakeTime: value.wakeTime,
        notes: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SymptomsLog;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: SymptomsLog;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WaterIntakeEntry;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: WaterIntakeEntry;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n17(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ocean: null;
} | {
    cloud: null;
} | {
    night: null;
} | {
    sunset: null;
}): Theme {
    return "ocean" in value ? Theme.ocean : "cloud" in value ? Theme.cloud : "night" in value ? Theme.night : "sunset" in value ? Theme.sunset : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lg: null;
} | {
    sm: null;
} | {
    base: null;
}): FontSize {
    return "lg" in value ? FontSize.lg : "sm" in value ? FontSize.sm : "base" in value ? FontSize.base : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Goal;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: Goal;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Goal_n30(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CycleLog;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: CycleLog;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CycleLog_n4(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    abandoned: null;
}): GoalStatus {
    return "active" in value ? GoalStatus.active : "completed" in value ? GoalStatus.completed : "abandoned" in value ? GoalStatus.abandoned : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Habit;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: Habit;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _JournalEntry;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: JournalEntry;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_JournalEntry_n38(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gratitude: null;
} | {
    regular: null;
}): JournalType {
    return "gratitude" in value ? JournalType.gratitude : "regular" in value ? JournalType.regular : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MoodEntry;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: MoodEntry;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_MoodEntry_n47(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SleepLog;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: SleepLog;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_SleepLog_n52(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _QuizResult;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: QuizResult;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _HabitCompletion;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: HabitCompletion;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SafetyPlan;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: SafetyPlan;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alreadyExists: null;
} | {
    invalidInput: string;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): {
    __kind__: "alreadyExists";
    alreadyExists: null;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "alreadyExists" in value ? {
        __kind__: "alreadyExists",
        alreadyExists: value.alreadyExists
    } : "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CycleLog>): Array<CycleLog> {
    return value.map((x)=>from_candid_CycleLog_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JournalEntry>): Array<JournalEntry> {
    return value.map((x)=>from_candid_JournalEntry_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MoodEntry>): Array<MoodEntry> {
    return value.map((x)=>from_candid_MoodEntry_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SleepLog>): Array<SleepLog> {
    return value.map((x)=>from_candid_SleepLog_n52(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
